Controllers/GroupsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Students.Data;
using Students.Models;

namespace Students.Controllers
{

    //Контроллер для управления группами, большая часть его методов доступна
    //только администраторам и профессорам
    [ApiExplorerSettings(IgnoreApi = true)]
    [Authorize(Roles = "admin, professor")]
    public class GroupsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public GroupsController(ApplicationDbContext context)
        {
            _context = context;
        }

        //Обработчик главной страницы, доступен анонимным пользователям
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            ViewBag.IsAdmin = false;
            if (User.Identity.IsAuthenticated)
            {
                ViewBag.IsAdmin = User.IsInRole("admin") || User.IsInRole("professor");
            }
            return View(await _context.Groups.ToListAsync());
        }

        //Страница просмотра группы, доступна всем авторизированным пользователям
        [Authorize(Roles = "admin, student, professor")]
        public async Task<IActionResult> Details(int? id)
        {
            //Если id нет, возвращаем 404
            if (id == null)
            {
                return NotFound();
            }
            //Пытаемся найти группу
            var @group = await _context.Groups
                .FirstOrDefaultAsync(m => m.Id == id);
            //Если группа не найдена, возвращаем 404
            if (@group == null)
            {
                return NotFound();
            }
            return View(@group);
        }

        //Обработчик GET запроса для страницы создания группы
        public IActionResult Create()
        {
            return View();
        }

        //Обработчик POST запроса для страницы создания группы
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Active")] Group @group)
        {
            if (_context.Groups.FirstOrDefault(g => g.Name == @group.Name) != null)
            {
                ModelState.AddModelError("Name", "Group with such name already exists");
            }
            //Проверяем валидность данных
            if (ModelState.IsValid)
            {
                _context.Add(@group);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(@group);
        }

        //Обработчик GET запроса для страницы редактирования группы
        public async Task<IActionResult> Edit(int? id)
        {
            //Если id нет
            if (id == null)
            {
                //Возвращаем 404
                return NotFound();
            }
            //Ищем в базе группу
            var @group = await _context.Groups.FindAsync(id);
            //Если её нет, возвращаем 404
            if (@group == null)
            {
                return NotFound();
            }
            return View(@group);
        }

        //Обработчик POST запроса для страницы редактирования группы
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Active")] Group @group)
        {
            if (id != @group.Id)
            {
                return NotFound();
            }
            if (_context.Groups.FirstOrDefault(g => g.Name == @group.Name && g.Id != @group.Id) != null)
            {
                ModelState.AddModelError("Name", "Group with such name already exists");
            }
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(@group);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GroupExists(@group.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(@group);
        }
        //Обработчик GET запроса страницы удаления группы
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @group = await _context.Groups
                .FirstOrDefaultAsync(m => m.Id == id);
            if (@group == null)
            {
                return NotFound();
            }

            return View(@group);
        }

        //Обработчик POST запроса страницы удаления группы
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var @group = await _context.Groups.FindAsync(id);
            _context.Groups.Remove(@group);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        //Метод для проверки сущестования группы с указанным id
        private bool GroupExists(int id)
        {
            return _context.Groups.Any(e => e.Id == id);
        }
    }
}

Controllers/PairsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Students.Data;
using Students.Models;

namespace Students.Controllers
{
    //Контроллер для управления парами, большая часть его методов доступна
    //только администраторам и профессорам
    [ApiExplorerSettings(IgnoreApi = true)]
    [Authorize(Roles = "admin, professor")]
    public class PairsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PairsController(ApplicationDbContext context)
        {
            _context = context;
        }

        //Обработчик главной страницы со списком пар, доступна всем
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            ViewBag.IsAdmin = false;
            if (User.Identity.IsAuthenticated)
            {
                ViewBag.IsAdmin = User.IsInRole("admin") || User.IsInRole("professor");
            }
            var applicationDbContext = _context.Pairs.Include(p => p.Group).Include(p => p.Professor).Where(p => p.Group.Active);
            return View(await applicationDbContext.ToListAsync());
        }

        //Обработчик страницы просмотра пар, доступна всем авторизированным пользователям
        [Authorize(Roles = "admin, student, professor")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pair = await _context.Pairs
                .Include(p => p.Group)
                .Include(p => p.Professor)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (pair == null || !pair.Group.Active)
            {
                return NotFound();
            }

            return View(pair);
        }

        //Обработчик GET запроса страницы создания пары
        public async Task<IActionResult> Create()
        {
            ViewBag.Groups = await _context.Groups.ToListAsync();
            ViewBag.Professors = await _context.Professors.ToListAsync();
            return View();
        }

        //Обработчик POST запроса страницы создания пары
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Date,GroupId,ProfessorId")] Pair pair)
        {
            if (ModelState.IsValid)
            {
                _context.Add(pair);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            ViewBag.Groups = await _context.Groups.ToListAsync();
            ViewBag.Professors = await _context.Professors.ToListAsync();

            return View(pair);
        }

        //Обработчик GET запроса страницы редактирования пары
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pair = await _context.Pairs.FindAsync(id);
            if (pair == null)
            {
                return NotFound();
            }

            ViewBag.Groups = await _context.Groups.ToListAsync();
            ViewBag.Professors = await _context.Professors.ToListAsync();

            return View(pair);
        }

        //Обработчик POST запроса страницы редактирования пары
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Date,GroupId,ProfessorId")] Pair pair)
        {
            if (id != pair.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(pair);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PairExists(pair.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewBag.Groups = new SelectList(_context.Groups, "Id", "Name");
            ViewBag.Professors = new SelectList(_context.Professors, "Id", "Name");
            return View(pair);
        }

        //Обработчик GET запроса страницы удаления пары
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pair = await _context.Pairs
                .Include(p => p.Group)
                .Include(p => p.Professor)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (pair == null)
            {
                return NotFound();
            }

            return View(pair);
        }

        //Обработчик POST запроса страницы удаления пары
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var pair = await _context.Pairs.FindAsync(id);
            _context.Pairs.Remove(pair);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        //Метод проверки существования пары с указанным id
        private bool PairExists(int id)
        {
            return _context.Pairs.Any(e => e.Id == id);
        }
    }
}

Controllers/ProfessorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Students.Data;
using Students.Models;

namespace Students.Controllers
{
    //Контроллер для управления профессорами, большая часть его методов доступна
    //только администраторам и профессорам
    [Authorize(Roles = "admin, professor")]
    [ApiExplorerSettings(IgnoreApi = true)]
    public class ProfessorsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ProfessorsController(ApplicationDbContext context)
        {
            _context = context;
        }

        //Страница списка профессоров, доступна всем
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            ViewBag.IsAdmin = false;
            if (User.Identity.IsAuthenticated)
            {
                ViewBag.IsAdmin = User.IsInRole("admin") || User.IsInRole("professor");
            }
            return View(await _context.Professors.ToListAsync());
        }

        //Страница просмотра профессора, доступна только авторизированным пользователям
        [Authorize(Roles = "admin, student, professor")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var professor = await _context.Professors
                .FirstOrDefaultAsync(m => m.Id == id);
            if (professor == null)
            {
                return NotFound();
            }

            return View(professor);
        }
        
        //Обработчик GET запроса страницы создания профессора
        public IActionResult Create()
        {
            return View();
        }

        //Обработчик POST запроса страницы создания профессора
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name")] Professor professor)
        {
            if (ModelState.IsValid)
            {
                _context.Add(professor);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(professor);
        }

        //Обработчик GET запроса страницы редактирования профессора
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var professor = await _context.Professors.FindAsync(id);
            if (professor == null)
            {
                return NotFound();
            }
            return View(professor);
        }

        //Обработчик POST запроса страницы редактирования профессора
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name")] Professor professor)
        {
            if (id != professor.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(professor);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProfessorExists(professor.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(professor);
        }

        //Обработчик GET запроса страницы удаления профессора
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var professor = await _context.Professors
                .FirstOrDefaultAsync(m => m.Id == id);
            if (professor == null)
            {
                return NotFound();
            }

            return View(professor);
        }

        //Обработчик POST запроса страницы редактирования профессора
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var professor = await _context.Professors.FindAsync(id);
            _context.Professors.Remove(professor);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        //Метод проверки существования профессора с указанным id
        private bool ProfessorExists(int id)
        {
            return _context.Professors.Any(e => e.Id == id);
        }
    }
}

Views/Shared/_GroupList.cshtml
@model IEnumerable<Students.Models.Group>

<div class="list-div">
    <table class="table-condensed">
        <tr>
            <th>Id</th>
            <th>Имя группы</th>
            <th>Активность</th>
            @if (User.Identity.IsAuthenticated)
            {
                <th>Посмотреть</th>}

            @if (ViewBag.IsAdmin)
            {
                <th>Редактировать</th>
                <th>Удалить</th>
            }
        </tr>
        @foreach (var group in Model)
        {
            <tr>
                <td>@group.Id</td>
                <td>@group.Name</td>
                @if (group.Active)
                {
                    <td>Активна</td>
                }
                else { 
                    <td>Не активна</td>
                }
                @if (User.Identity.IsAuthenticated)
                {
                    <td>
                        <button type="button" class="btn-success">
                            <a class="btn-success" asp-action="Details" asp-controller="Groups" asp-route-id="@group.Id">
                                Посмотреть
                            </a>
                        </button>
                    </td>
                }
                @if (ViewBag.IsAdmin)
                {
                    <td>
                        <button type="button" class="btn-warning">
                            <a class="btn-warning" asp-action="Edit" asp-controller="Groups" asp-route-id="@group.Id">
                                Редактировать
                            </a>
                        </button>
                    </td>
                    <td>
                        <button type="button" class="btn-danger">
                            <a class="btn-danger" asp-action="Delete" asp-controller="Groups" asp-route-id="@group.Id">
                                Удалить
                            </a>
                        </button>
                    </td>
                }
            </tr>
        }
    </table>
    @if (ViewBag.IsAdmin)
    {
        <button type="button" class="btn-primary">
            <a class="btn-primary" asp-controller="Groups" asp-action="Create">Создать</a>
        </button>
    }
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Students</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" asp-append-version="true">
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Students</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Главная</a></li>
                    <li><a asp-area="" asp-controller="Student" asp-action="Index">Студенты</a></li>
                    <li><a asp-area="" asp-controller="Groups" asp-action="Index">Группы</a></li>
                    <li><a asp-area="" asp-controller="Pairs" asp-action="Index">Пары</a></li>
                    <li><a asp-area="" asp-controller="Professors" asp-action="Index">Профессора</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Контакты</a></li>
                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - Students</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Shared/_PairsList.cshtml
@model IEnumerable<Students.Models.Pair>

<div class="list-div">
    <table class="table-condensed">
        <tr>
            <th>Id</th>
            <th>Дата</th>
            <th>Группа</th>
            <th>Профессор</th>
            @if (User.Identity.IsAuthenticated)
            {
                <th>Посмотреть</th>}
            @if (ViewBag.IsAdmin)
            {
                <th>Редактировать</th>
                <th>Удалить</th>
            }
        </tr>
        @foreach (var pair in Model)
        {
            <tr>
                <td>@pair.Id</td>
                <td>@pair.Date.ToString()</td>
                <td>@pair.Group.Name</td>
                <td>@pair.Professor.Name</td>
                @if (User.Identity.IsAuthenticated)
                {
                    <td>
                        <button type="button" class="btn-success">
                            <a class="btn-success" asp-action="Details" asp-controller="Pairs" asp-route-id="@pair.Id">
                                Посмотреть
                            </a>
                        </button>
                    </td>
                }
                @if (ViewBag.IsAdmin)
                {
                    <td>
                        <button type="button" class="btn-warning">
                            <a class="btn-warning" asp-action="Edit" asp-controller="Pairs" asp-route-id="@pair.Id">
                                Редактировать
                            </a>
                        </button>
                    </td>
                    <td>
                        <button type="button" class="btn-danger">
                            <a class="btn-danger" asp-action="Delete" asp-controller="Pairs" asp-route-id="@pair.Id">
                                Удалить
                            </a>
                        </button>
                    </td>
                }
            </tr>
        }
    </table>
    @if (ViewBag.IsAdmin)
    {
        <button type="button" class="btn-primary">
            <a class="btn-primary" asp-controller="Pairs" asp-action="Create">Создать</a>
        </button>
    }
</div>

Views/Shared/_ProfessorsList.cshtml
@model IEnumerable<Students.Models.Professor>

<div class="list-div">
    <table class="table-condensed">
        <tr>
            <th>Id</th>
            <th>Имя</th>
            @if (User.Identity.IsAuthenticated)
            {
                <th>Посмотреть</th>}
            @if (ViewBag.IsAdmin)
            {
                <th>Редактировать</th>
                <th>Удалить</th>
            }
        </tr>
        @foreach (var professor in Model)
        {
            <tr>
                <td>@professor.Id</td>
                <td>@professor.Name</td>
                @if (User.Identity.IsAuthenticated)
                {
                    <td>
                        <button type="button" class="btn-success">
                            <a class="btn-success" asp-action="Details" asp-controller="Professors" asp-route-id="@professor.Id">
                                Посмотреть
                            </a>
                        </button>
                    </td>
                }
                @if (ViewBag.IsAdmin)
                {
                    <td>
                        <button type="button" class="btn-warning">
                            <a class="btn-warning" asp-action="Edit" asp-controller="Professors" asp-route-id="@professor.Id">
                                Редактировать
                            </a>
                        </button>
                    </td>
                    <td>
                        <button type="button" class="btn-danger">
                            <a class="btn-danger" asp-action="Delete" asp-controller="Professors" asp-route-id="@professor.Id">
                                Удалить
                            </a>
                        </button>
                    </td>
                }
            </tr>
        }
    </table>
    @if (ViewBag.IsAdmin)
    {
        <button type="button" class="btn-primary">
            <a class="btn-primary" asp-controller="Professors" asp-action="Create">Создать</a>
        </button>
    }
</div>

Views/Shared/_StudentsList.cshtml
@model IEnumerable<Students.Models.Student>

<div class="list-div">
    <table class="table-condensed">
        <tr>
            <th>Id</th>
            <th>Имя</th>
            <th>Имя группы</th>
            @if (User.Identity.IsAuthenticated)
            {
                <th>Посмотреть</th>}
            @if (ViewBag.IsAdmin)
            {
                <th>Редактировать</th>
                <th>Удалить</th>
            }
        </tr>
        @foreach (var student in Model)
        {
            <tr>
                <td>@student.Id</td>
                <td>@student.Name</td>
                <td>@student.Group.Name</td>
                @if (User.Identity.IsAuthenticated)
                {
                    <td>
                        <button type="button" class="btn-success">
                            <a class="btn-success" asp-action="Details" asp-controller="Student" asp-route-id="@student.Id">
                                Посмотреть
                            </a>
                        </button>
                    </td>
                }
                @if (ViewBag.IsAdmin)
                {
                    <td>
                        <button type="button" class="btn-warning">
                            <a class="btn-warning" asp-action="Edit" asp-controller="Student" asp-route-id="@student.Id">
                                Редактировать
                            </a>
                        </button>
                    </td>
                    <td>
                        <button type="button" class="btn-danger">
                            <a class="btn-danger" asp-action="Delete" asp-controller="Student" asp-route-id="@student.Id">
                                Удалить
                            </a>
                        </button>
                    </td>
                }
            </tr>
        }
    </table>
    @if (ViewBag.IsAdmin)
    {
        <button type="button" class="btn-primary">
            <a class="btn-primary" asp-controller="Student" asp-action="Create">Создать</a>
        </button>
    }
</div>